spring:
  datasource:
    url: jdbc:h2:mem:client_db;
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
server:
  port: 8082